import { Environments, PipelineStatus } from './types'

function minutesAgo(min) {
  return new Date(Date.now() - min * 60 * 1000).toISOString()
}

/**
 * A pipeline in this app represents "a repo workflow on a branch" that deploys
 * through Dev -> Staging -> Production.
 */
export function createInitialPipelines() {
  return [
    {
      id: 'p1',
      repo: 'payments-service',
      branch: 'main',
      team: 'Payments',
      environment: Environments.staging,
      status: PipelineStatus.failed,
      lastRunAt: minutesAgo(12),
      durationSec: 248,
      actor: 'sadaf',
      commitSha: 'a1b2c3d',
      prNumber: 418,
      lastError:
        'Step "integration-tests" failed: ECONNREFUSED to staging dependency.',
      lastStableTag: 'v2.14.3',
      currentReleaseTag: 'v2.15.0-rc.2',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p2',
      repo: 'web-frontend',
      branch: 'release/2.8',
      team: 'Web',
      environment: Environments.dev,
      status: PipelineStatus.running,
      lastRunAt: minutesAgo(2),
      durationSec: 91,
      actor: 'ali',
      commitSha: 'd4e5f6a',
      prNumber: 0,
      lastError: '',
      lastStableTag: 'v2.7.9',
      currentReleaseTag: 'v2.8.0',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p3',
      repo: 'orders-service',
      branch: 'main',
      team: 'Core',
      environment: Environments.production,
      status: PipelineStatus.success,
      lastRunAt: minutesAgo(55),
      durationSec: 312,
      actor: 'sara',
      commitSha: '9f8e7d6',
      prNumber: 402,
      lastError: '',
      lastStableTag: 'v1.22.0',
      currentReleaseTag: 'v1.23.0',
      approvals: {
        production: { required: true, approved: true, note: 'Checked dashboards' },
      },
    },
    {
      id: 'p4',
      repo: 'infra-terraform',
      branch: 'main',
      team: 'Platform',
      environment: Environments.dev,
      status: PipelineStatus.queued,
      lastRunAt: minutesAgo(1),
      durationSec: 0,
      actor: 'fatima',
      commitSha: '0aa12bc',
      prNumber: 511,
      lastError: '',
      lastStableTag: 'v0.9.4',
      currentReleaseTag: 'v0.10.0',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p5',
      repo: 'notifications-service',
      branch: 'main',
      team: 'Messaging',
      environment: Environments.staging,
      status: PipelineStatus.cancelled,
      lastRunAt: minutesAgo(25),
      durationSec: 33,
      actor: 'omar',
      commitSha: '7aa9b10',
      prNumber: 0,
      lastError: 'Cancelled by user after noticing wrong env var.',
      lastStableTag: 'v3.1.1',
      currentReleaseTag: 'v3.2.0',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p6',
      repo: 'auth-service',
      branch: 'hotfix/jwt-expiry',
      team: 'Security',
      environment: Environments.dev,
      status: PipelineStatus.success,
      lastRunAt: minutesAgo(6),
      durationSec: 141,
      actor: 'sadaf',
      commitSha: 'bc12def',
      prNumber: 533,
      lastError: '',
      lastStableTag: 'v4.0.2',
      currentReleaseTag: 'v4.0.3',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p7',
      repo: 'catalog-service',
      branch: 'main',
      team: 'Core',
      environment: Environments.staging,
      status: PipelineStatus.running,
      lastRunAt: minutesAgo(4),
      durationSec: 167,
      actor: 'junaid',
      commitSha: 'c0ffee1',
      prNumber: 399,
      lastError: '',
      lastStableTag: 'v1.8.0',
      currentReleaseTag: 'v1.9.0',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p8',
      repo: 'shipping-service',
      branch: 'main',
      team: 'Logistics',
      environment: Environments.production,
      status: PipelineStatus.running,
      lastRunAt: minutesAgo(1),
      durationSec: 28,
      actor: 'sara',
      commitSha: 'deadbee',
      prNumber: 0,
      lastError: '',
      lastStableTag: 'v5.4.2',
      currentReleaseTag: 'v5.5.0',
      approvals: {
        production: { required: true, approved: true, note: 'Routine release' },
      },
    },
    {
      id: 'p9',
      repo: 'analytics-batch',
      branch: 'main',
      team: 'Data',
      environment: Environments.dev,
      status: PipelineStatus.failed,
      lastRunAt: minutesAgo(9),
      durationSec: 410,
      actor: 'ali',
      commitSha: 'face123',
      prNumber: 0,
      lastError: 'Python dependency resolution failed (conflicting pins).',
      lastStableTag: 'v0.6.8',
      currentReleaseTag: 'v0.7.0',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p10',
      repo: 'mobile-api',
      branch: 'main',
      team: 'Mobile',
      environment: Environments.staging,
      status: PipelineStatus.success,
      lastRunAt: minutesAgo(18),
      durationSec: 201,
      actor: 'fatima',
      commitSha: '123abcd',
      prNumber: 620,
      lastError: '',
      lastStableTag: 'v6.2.0',
      currentReleaseTag: 'v6.3.0',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p11',
      repo: 'feature-flags',
      branch: 'main',
      team: 'Platform',
      environment: Environments.dev,
      status: PipelineStatus.queued,
      lastRunAt: minutesAgo(0.5),
      durationSec: 0,
      actor: 'omar',
      commitSha: 'bead222',
      prNumber: 0,
      lastError: '',
      lastStableTag: 'v1.0.0',
      currentReleaseTag: 'v1.1.0',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
    {
      id: 'p12',
      repo: 'gke-deployer',
      branch: 'main',
      team: 'Platform',
      environment: Environments.staging,
      status: PipelineStatus.success,
      lastRunAt: minutesAgo(31),
      durationSec: 88,
      actor: 'sadaf',
      commitSha: 'aa11bb2',
      prNumber: 0,
      lastError: '',
      lastStableTag: 'v0.3.1',
      currentReleaseTag: 'v0.3.2',
      approvals: {
        production: { required: true, approved: false, note: '' },
      },
    },
  ]
}

